name: Import Riksdagsdata

on:
  workflow_dispatch:  # Körs manuellt
  schedule:
    - cron: '0 3 * * *'  # Körs varje natt kl 03:00

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch dotenv @supabase/supabase-js

      - name: Run import script
        run: node importAll.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
